spring.application.name=awsapplication
aws.region=ap-south-1
aws.sqs.queue-url=https://sqs.ap-south-1.amazonaws.com/423014875432/xmlq
db.secret.name=dbcreds
server.port=8080
server.address=0.0.0.0
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1
jwt.secret=awsapp12@$%^3456788765432awsapp12@$%^3456788765432
